laika.title = "Work with images"
laika.navigationOrder = [
  "exact-views.md",
  "combine-aligned-images.md",
  "filter-and-gradients.md",
  "masks-and-morphology.md",
  "read-nifti.md",
  "display-intaglio.md"
]
